apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      labels:
        app: shoppingcart
    spec:
      containers:
      - name: shoppingcart
        image: sabarishselva23/shoppingcart:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-service
spec:
  type: NodePort
  selector:
    app: shoppingcart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
